### PR TITLE
Add aic bic functions

### PR DESCRIPTION
**Pull request by fperraudeau**
When I run "check", I get no errors, warnings, or notes. New functions (nParams, zinb.AIC, zinb.BIC) are documented.

### CODE REVIEW

**Comment by drisso** [comment]
Hi @fperraudeau 

I've reviewed the pull request and everything looks fine!

I know that this is very picky, but what about renaming the two functions zinbAIC and zinbBIC (without the ".")? We're not using that coding stile in this package (even though we're using a mix of camelCase and underscores let's try to avoid the dots...) The main reason being that in S3 this would read as the zinb method for the AIC and BIC objects, when it's actually the other way round...

If you don't mind changing the function names, I will merge to master!

**Comment by fperraudeau** [comment]
Hi Davide,

I changed the names to zinbAIC and zinbBIC. The package still passes the check with no error, warning, or note. You can merge whenever you feel.

**Comment by fperraudeau** [comment]
@drisso, could you wait the end of the week-end to review the pull request? I would also like to add a function to compute the observational weights.

**Comment by drisso** [comment]
Is this all you wanted to add? Can I go ahead and merge?

Thanks!

**Comment by fperraudeau** [comment]
Yes, this is it. Thank you, Davide.

**Comment by drisso** [comment]
@fperraudeau I've pushed the edits to Github and Bioconductor! (Version 0.99.9)

**Comment by fperraudeau** [comment]
Awesome. Thanks, Davide.

**Pull request merged**
